# Generated by Django 4.0.3 on 2022-05-27 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=32)),
                ('text', models.TextField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('Rent', 'Rent'),
                            ('Mortgage', 'Mortgage'),
                            ('Bills', 'Bills'),
                            ('Transportation', 'Transportation'),
                            ('Clothing', 'Clothing'),
                            ('Healthcare', 'Healthcare'),
                            ('Food', 'Food'),
                            ('Insurance', 'Insurance'),
                            ('Kids', 'Kids'),
                            ('Culture', 'Culture'),
                            ('Vacations', 'Vacations'),
                            ('Other', 'Other'),
                        ],
                        default='Other',
                        max_length=32,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                (
                    'user',
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
